# Generated by Django 3.2.9 on 2022-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='resfile',
            field=models.FileField(default='', upload_to='resume/pdfs/'),
        ),
    ]
