# Generated by Django 3.2.9 on 2022-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20220512_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make_Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('loc1', models.CharField(max_length=500)),
                ('loc2', models.CharField(max_length=500)),
                ('seducation', models.CharField(max_length=1000)),
                ('sseducation', models.CharField(max_length=1000)),
                ('graduation', models.CharField(max_length=1000)),
                ('por', models.CharField(max_length=2000)),
                ('course', models.CharField(max_length=2000)),
                ('project', models.CharField(max_length=2000)),
                ('skill', models.CharField(max_length=500)),
                ('blog', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=500)),
                ('other', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='resume/pdfs/'),
        ),
    ]
