# Generated by Django 3.0 on 2022-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20220525_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_resume',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='course',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='github',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='loc1',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='loc2',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='other',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='por',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='project',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='seducation',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='make_resume',
            name='sseducation',
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity1end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity1info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity1start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity2end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity2info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity2start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity3end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity3info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='activity3start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='board10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='board12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='college',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='cpi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='cpi10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='cpi12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='endyear',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p1end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p1info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p1start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p2end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p2info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p2start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p3end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p3info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='p3start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj1end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj1info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj1start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj2end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj2info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj2start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj3end',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj3info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='proj3start',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='ptitle1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='ptitle2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='ptitle3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='roll',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='startyear',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='year10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='make_resume',
            name='year12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='make_resume',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='make_resume',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
