# Generated by Django 3.0 on 2022-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_make_resume_techskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('roll', models.CharField(default='', max_length=100)),
                ('mode', models.CharField(default='', max_length=100)),
                ('pref1', models.CharField(default='', max_length=100)),
                ('pref2', models.CharField(default='', max_length=100)),
                ('pref3', models.CharField(default='', max_length=100)),
                ('pref4', models.CharField(default='', max_length=100)),
                ('pref5', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
