# Generated by Django 3.0 on 2022-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='pref2',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='pref3',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='pref4',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='pref5',
        ),
        migrations.AddField(
            model_name='apply',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
