# Generated by Django 3.0 on 2022-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20220529_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='company',
        ),
        migrations.AddField(
            model_name='apply',
            name='pref2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apply',
            name='pref3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
