# Generated by Django 4.2.1 on 2023-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_apply_pref4_alter_account_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='pref5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apply',
            name='resumelink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='apply',
            name='pref4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
